version: 1.0.{build}
branches:
  only:
    - main
skip_non_tags: true
image: Ubuntu2004
environment:
  README_ASSETS_PREFIX: ""
  NUGET_API_KEY: NUGET_API_KEY
build_script:
  - sh: >-
      set -e

      npm install --global @devcontainers/cli

      devcontainer build --workspace-folder .
deploy_script:
  - sh: >-
      set -e

      devcontainer up --workspace-folder .

      devcontainer exec --workspace-folder . \
        --remote-env README_ASSETS_PREFIX=${README_ASSETS_PREFIX} \
        --remote-env NUGET_API_KEY=${NUGET_API_KEY} \
        pnpm run publish
